"""Update Project (add details)

Revision ID: f97c0a5f4f65
Revises: 1bf0987ee356
Create Date: 2024-08-17 14:57:00.799350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97c0a5f4f65'
down_revision = '1bf0987ee356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
